export const LIMITS = {
  MAX_WORKSPACES_PER_USER: 1,
  MAX_MEMBERS_PER_WORKSPACE: 5,
  INVITE_EXPIRES_DAYS: 7,
  DISPLAY_NAME_MAX_LENGTH: 20,
  WORKSPACE_NAME_MAX_LENGTH: 50,
  WAVE_HISTORY_LIMIT: 50,
} as const;
